[[language]]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
auto-format = true
file-types = ["tsx"]
name = "tsx"
scope = "source.tsx"

[[language]]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
auto-format = true
file-types = ["ts", "mts"]
name = "typescript"
scope = "source.ts"

[[language]]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
auto-format = true
file-types = ["jsx"]
name = "jsx"
scope = "source.jsx"

[[language]]
auto-format = true
file-types = ["js", "mjs", "cjs"]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
name = "javascript"
scope = "source.javascript"

[[language]]
auto-format = true
file-types = ["css"]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
name = "css"
scope = "source.css"

[[language]]
auto-format = true
file-types = ["html"]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
name = "html"
scope = "source.html"

[[language]]
auto-format = true
file-types = ["json"]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
name = "json"
scope = "source.json"
language-servers = [
  "vscode-json-language-server",
  "deps-lsp"
]

[[language]]
auto-format = true
file-types = ["md"]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
name = "markdown"
scope = "source.markdown"

[[language]]
name = "toml"
language-servers = ["deps-lsp"]

[[language]]
auto-format = true
file-types = ["vue"]
formatter = { command = "biome", args = ["format", "--write", "--stdin-file-path", "%{buffer_name}"] }
language-servers = [
  # "vuels",
  "typescript-language-server",
  "tailwindcss",
  "vscode-html-language-server",
  "vscode-css-language-server",
  "biome"
]
name = "vue"
scope = "source.vue"

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript-language-server.config]
hostInfo = "helix"

[language-server.typescript-language-server.config.typescript]
tsdk = "/usr/lib/node_modules/typescript/lib"

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/usr/lib/node_modules/@vue/typescript-plugin"
languages = ["vue"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server.config]
provideFormatter = false
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]
root-pattern = ["tailwind.config.js", "tailwind.config.cjs", "postcss.config.js"]
file-types = ["html", "css", "javascript", "typescript", "jsx", "tsx", "vue"]

[language-server.deps-lsp]
command = "deps-lsp"
args = ["--stdio"]
